### PR TITLE
Add responsiveness to the site #36

### PR DESCRIPTION
**Pull request by harshit1142**
Now: No horizontal slider
127 0 0 1_5500 - Google Chrome 23-10-2023 21_10_19

Before: There was a horizontal slider
127 0 0 1_5500 - Google Chrome 23-10-2023 21_10_49

### CODE REVIEW

**Comment by Neel-07** [comment]
@harshit1142 the navbar looks out of context from the side, leaving some spaces. could you fix that.

**Comment by harshit1142** [comment]
@Neel-07  let me try

**Comment by Neel-07** [comment]
@harshit1142 by adding responsiveness i mean  designing and developing the site in a way that allows it to adapt and display correctly on a wide range of devices and screen sizes, providing an optimal user experience regardless of whether the visitor is using a desktop computer, tablet, smartphone, or other devices.

**Comment by harshit1142** [comment]
@Neel-07  Yes,got

**Comment by harshit1142** [comment]
@Neel-07 


Temperature Convertor - Google Chrome 24-10-2023 11_09_28


Temperature Convertor - Google Chrome 24-10-2023 11_29_05
Temperature Convertor - Google Chrome 24-10-2023 11_28_52

**Review by Neel-07 — APPROVED** [review]

**Comment by harshit1142** [comment]
Please Add hacktoberfest label if possible.

**Pull request merged**
