### PR TITLE
Added a block in the footer which shows no of visitors in the site issue #30

### PR DESCRIPTION
**Pull request by AryanSaxenaa**
Added a block in the footer that shows no visitors to the site. issue #30 
image
The counter will show the number of times the website has been viewed.

### CODE REVIEW

**Comment by Neel-07** [comment]
hello @AryanSaxenaa I wanted to discuss some enhancements to the way we've integrated the visitor counter on our website. Making these improvements will not only enhance the appearance of the counter but also improve its overall functionality and user experience. Here are the changes I'd like to request, styling-Please apply CSS styles to the visitor counter to make it visually appealing and in line with the design of our website. You can control the font size, color, and positioning to ensure it seamlessly blends with our website's aesthetics.

**Comment by AryanSaxenaa** [comment]
image
Tried to reflect the theme of the  website in the counter

**Comment by AryanSaxenaa** [comment]
image
Also can you look into this issue, It shows that this repository in not a praticipant in hacktoberfest

**Comment by Neel-07** [comment]
> image Tried to reflect the theme of the website in the counter

 change the width of the footer to 100 vw

**Comment by Neel-07** [comment]
> image Also can you look into this issue, It shows that this repository in not a praticipant in hacktoberfest

if you mention the issue number it will show that it is participating, else i can add the hacktoberfest  label to this pr and it will be fine.

**Comment by AryanSaxenaa** [comment]
Changed the width of the footer to 100vw

**Comment by Neel-07** [comment]
already merged the visitor counter part  in another  part.

**Pull request closed without merging**
