### PR TITLE
design: Upgrade the UI 

### PR DESCRIPTION
**Pull request by Abishkardhenga**
#8  fixed

I have made the Ui good than previous one and additionally I have added CopyLink feature so we can  invite the user to use our tool or learn more about it.

### CODE REVIEW

**Comment by Neel-07** [comment]
@Aabiskar-dhenga can you add a video or screenshots showing the changes.

**Comment by Abishkardhenga** [comment]
wait i will do that

**Comment by Abishkardhenga** [comment]
download
 here it is

**Comment by Neel-07** [comment]
@Aabiskar-dhenga, the previous one was looking better, just change the colour code  to the previous and send a screenshot.

**Comment by Abishkardhenga** [comment]
> @Aabiskar-dhenga, the previous one was looking better, just change the colour code to the previous and send a screenshot.

ok

**Comment by Abishkardhenga** [comment]
seee hereee :
download

**Comment by Neel-07** [comment]
@Aabiskar-dhenga  the changes have been made, so closing your pr for now. Star the repo and keep and eye on the new issues. 
Dont mind buddy but ui was not appealing much, sorry for not merging your pr

**Pull request closed without merging**
